blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/your-invite
    about: Join our Discord server for questions and discussions
  - name: 💡 GitHub Discussions
    url: https://github.com/yourusername/emperione-discord/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/yourusername/emperione-discord/tree/main/docs
    about: Read the documentation for setup and usage guides
